### ISSUE TITLE
downloading / installation instructions

### ISSUE THREAD

**Issue by abubelinha** [maurobio/freedelta#1]
Hi @maurobio 
I see [this repository is pretty new,](https://mailman.science.uu.nl/pipermail/delta-l/2021-August/003142.html) so perhaps this is just a matter of time, but I will suggest some updates:

- You mention the Free Delta Editor is written in FreePascal/Lazarus, and I only see source code here. I suggest to provide some minimal explanations of how to install the software from that sources.
Otherwise, could you please provide direct links to binaries from here too [as you do in sourceforge](http://freedelta.sourceforge.net/fde/#Download)?
- Regarding those binaries, I wonder if it is somehow possible to get a portable Windows version which could be launched from an USB key on different computers.
- I also suggest to migrate the freedelta info pages from [freedelta.sourceforge.net](http://freedelta.sourceforge.net/) to github (perhaps easier to maintain here). 
BTW, the link to [delta-l mailing list](https://mailman.science.uu.nl/mailman/listinfo/delta-l) from sf is broken.

Thanks a lot for your work!

**Comment by maurobio** [comment]
Thanks for your message. 

Binary installation packages are available from the "Releases" page, as is the standard in GitHub repositories.

"Portable" versions just work on Windows and we do not provide support for features which work only on Windows (with the very annoying exception of the IntKey program, just because it is available only on Windows).

GitHub is mainly intended as a source code repository; SourceForge is our main all website and will information pages will be kept there.

The broken link for the DELTA-L discussion list in the main information page of SourceForge has been fixed.

Hope this helps.

Regards,

**Comment by abubelinha** [comment]
Thanks for your fast reply @maurobio !!
I was editing my original post because I had noticed virus in my download from SF.

**Comment by maurobio** [comment]
There are no such thing as a "virus" in the SourceForge downloads, that are exactly the same as are made available form the "Releases" page here on GitHub. It is just bullshit from AV software under M$-Windows (which are more of a nuisance than any real "help").

**Comment by abubelinha** [comment]
Good to know.  Anyway after seeing that false positive I got curious enough to check the FreePascal/Lazarus link and it looks interesting to me as well.
 
I take the opportunity to ask about other open source projects and libraries in the freedelta sourceforge page.
What's the differences between Pascal and FreePascal/Lazarus?
PyDELTA, DELTA C++ and Pascal libraries, etc ... are they all "finished" projects, in the sense that no new development is necessary? Or are they still in development stages and you plan to migrate their **source code** to github as well?

I see so many options that as a novice I get a bit confused about the best choice to start using DELTA.

Thanks a lot again
